# Generated by Django 2.2.6 on 2020-04-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Booking_Id', models.IntegerField(default=0)),
                ('Room_Id', models.IntegerField(default=0)),
                ('Items', models.ManyToManyField(through='first_app.Number', to='first_app.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='number',
            name='Items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Orders'),
        ),
        migrations.AddField(
            model_name='number',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Restaurant'),
        ),
    ]
