# Generated by Django 2.2.6 on 2020-04-29 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='Email',
            field=models.CharField(default='abc@gmail.com', max_length=30, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Name',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AlterField(
            model_name='personal',
            name='PhoneNumber',
            field=models.CharField(default='00000', max_length=12),
        ),
    ]
